In [ ]:
Yes, there is a difference in the data type of list_ and array_list.

list_ is a Python list which can contain elements of different data types, while array_list is a NumPy array which can only contain elements of the same data type.

To print the data types of both variables, you can use the type() function as follows:

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


In [61]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [62]:
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [63]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
